# Generated by Django 3.1.2 on 2020-10-03 06:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishedDateTime', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Educationlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField(null=True)),
                ('endDateTime', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GameConsole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picturePath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memberTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberTwo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picturePath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SexualOrientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picturePath', models.CharField(max_length=255)),
                ('gameConsole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.gameconsole')),
            ],
        ),
        migrations.CreateModel(
            name='MemberVideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.videogame')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateTimeField()),
                ('heightFeet', models.IntegerField()),
                ('heightInches', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=25)),
                ('latitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('longitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('personalText', models.TextField(default=None, null=True)),
                ('smokeTabacco', models.BooleanField(null=True)),
                ('drinkAlcohol', models.BooleanField(null=True)),
                ('smokeWeed', models.BooleanField(null=True)),
                ('haveBodyArt', models.BooleanField(null=True)),
                ('havePiercings', models.BooleanField(null=True)),
                ('haveChildren', models.BooleanField(null=True)),
                ('wantChildren', models.BooleanField(null=True)),
                ('party', models.BooleanField(null=True)),
                ('educationLevel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.educationlevel')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.gender')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sexualOrientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.sexualorientation')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.weight')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('priority', models.IntegerField()),
                ('isEnabled', models.BooleanField()),
                ('caption', models.CharField(max_length=255, null=True)),
                ('dateTimeUploaded', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberMovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movieGenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.moviegenre')),
            ],
        ),
        migrations.CreateModel(
            name='MemberGameConsole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameConsole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.gameconsole')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherMember', to=settings.AUTH_USER_MODEL)),
                ('memberInit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberInit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.system')),
            ],
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateTimeSent', models.DateTimeField()),
                ('isPublished', models.BooleanField()),
                ('fromMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemygamersite.inbox')),
            ],
        ),
    ]
