# Generated by Django 3.1.2 on 2020-10-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemygamersite', '0002_auto_20201002_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameconsole',
            old_name='picturePath',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='moviegenre',
            old_name='picturePath',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='picturePath',
            new_name='icon',
        ),
    ]
