# Generated by Django 3.1.2 on 2020-10-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemygamersite', '0005_auto_20201005_0418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educationlevel',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='membergameconsole',
            name='gameConsole',
        ),
        migrations.RemoveField(
            model_name='membergameconsole',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membermoviegenre',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membermoviegenre',
            name='movieGenre',
        ),
        migrations.RemoveField(
            model_name='membervideogame',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membervideogame',
            name='videoGame',
        ),
        migrations.DeleteModel(
            name='SexualOrientation',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='gameConsole',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.RenameField(
            model_name='memberattribute',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='personalText',
        ),
        migrations.DeleteModel(
            name='GameConsole',
        ),
        migrations.DeleteModel(
            name='MemberGameConsole',
        ),
        migrations.DeleteModel(
            name='MemberMovieGenre',
        ),
        migrations.DeleteModel(
            name='MemberVideoGame',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='VideoGame',
        ),
    ]
