# Generated by Django 3.1.2 on 2020-10-07 03:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemygamersite', '0007_auto_20201006_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberconnection',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberconnection',
            name='memberInit',
        ),
        migrations.RemoveField(
            model_name='memberphoto',
            name='member',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='likedMembers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='membersWhoLikeYou',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photos',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='drinkAlcohol',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='haveBodyArt',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='haveChildren',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='havePiercings',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='party',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='smokeTabacco',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='smokeWeed',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='wantChildren',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MemberAttribute',
        ),
        migrations.DeleteModel(
            name='MemberConnection',
        ),
        migrations.DeleteModel(
            name='MemberPhoto',
        ),
    ]
