# Generated by Django 3.1.2 on 2020-10-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemygamersite', '0008_auto_20201006_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='likedMembers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='membersWhoLikeYou',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photos',
            field=models.JSONField(null=True),
        ),
    ]
