# Generated by Django 3.1.2 on 2020-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemygamersite', '0009_auto_20201006_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='ageOlderDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='distanceDesired',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='drinkAlcoholDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='educationLevelDesired',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='haveBodyArtDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='haveChildrenDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='havePiercingsDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='isTallerDesired',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='partyDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='smokeTabaccoDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='smokeWeedDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='wantChildrenDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='weightDesired',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
