# Generated by Django 3.1.2 on 2020-10-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemygamersite', '0010_auto_20201006_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='gameConsoles',
            field=models.JSONField(null=True),
        ),
    ]
